### ISSUE TITLE
About the code of texture generation

### ISSUE THREAD

**Issue by wangwr1** [tomorrow1238/Ultraman#2]
Firstly, it's very kind of your team to release the code.
In the run part of the README file, you mention, "Then, you can generate texture with the following code: ./bash/{sh_file_name}". However, what is the file and file name? Please upload the file for texture generation, as this sh file is also missing from your file folder.
Thanks!

**Comment by tomorrow1238** [comment]
Thanks for your issue. {sh_file_name} means you can name this file name yourself, like run_experiment.sh Then, the scripts of previous steps will help you generate the final script used to generate the texture.
